### ISSUE TITLE
[rust] Add --no-ssl-certificate or --insecure (name like in curl) option, for customers with self-signed certs

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-lsp#24]

**Comment by olegklimov** [comment]
llm-ls has an example of how to do this I believe

**Comment by futurearchitec** [comment]
Thanks for creating this very important issue. It took me about an hour to find out the problem, using the refact-intellij plugin. The lsp-server started, but the completion request fails and following you get Server-500 errors. And the error source is the lsp-server, validating the self-signed certificate. It would be really nice to add a checkbox element to plugins settings-dialog, whether to disable SSL-Check or not. And this setting must be used in the plugin (intellij or VSCode) and passed through to the refact-lsp start up arguments as noted by @olegklimov .

@reymondzzzz : If possible, please check the refact-lsp documentation. It states, that it is used by the refact-VSCode plugin. That caused a small headache on my side, because with the refact-VSCode plugin everything works perfectly. And the reason is, as far as my research indicates, the refact-VSCode plugin is not using the refact-lsp server. In contrast to the refact-intellij plugin.

**Comment by olegklimov** [comment]
> refact-VSCode plugin is not using the refact-lsp

The Pre-Release version does!

**Comment by olegklimov** [comment]
https://github.com/smallcloudai/refact-lsp/pull/26/files

**Comment by olegklimov** [comment]
done
